others sever test 3 corrected .5

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -10,12 +10,12 @@ jobs:
 
     steps:
       - name: Stop PM2
-        run: pm2 stop jobs-api
+        run: pm2 stop jobs-api || true
       - name: Delete Existing repo
-        run: rm -r Jobs-Api
+        run: rm -r Jobs-Api || true
       - name: Clone From GitHub
         run: git clone git@github.com:ruby-tech1/Jobs-Api.git
       - name: Start Pm2
-        run: pm2 stop ecosystem.config.js
+        run: pm2 stop ecosystem.config.js || pm2 restart ecosystem.config.js
       - name: Restart Caddy
-        run: sudo systemctl restart caddy
+        run: sudo systemctl restart caddy || echo "Failed to restart Caddy"
