others sever test 3 corrected .8

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -14,7 +14,7 @@ jobs:
       - name: Delete Existing repo
         run: rm -r Jobs-Api || true
       - name: Clone From GitHub
-        run: git clone git@github.com:ruby-tech1/Jobs-Api.git || git clone https://github.com/ruby-tech1/Jobs-Api.git
+        run: git clone git@github.com:ruby-tech1/Jobs-Api.git || echo "Failed to clone repo"
       - name: Start Pm2
         run: pm2 start ecosystem.config.js || pm2 restart ecosystem.config.js
       - name: Restart Caddy
